version: "3.8"

services:
  atr_mosquitto:
    image: eclipse-mosquitto:2
    container_name: atr_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  atr_mina_app:
    build: .
    container_name: atr_mina_app
    depends_on:
      - atr_mosquitto
    environment:
      - MQTT_BROKER=atr_mosquitto
      - MQTT_PORT=1883
    volumes:
      - ./logs:/workspace/logs
      - ./routes:/workspace/routes
    command: ./build/atr_mina
    restart: on-failure
